'use strict';
(()=>{
const D=StudyData,E=Screening,$=s=>document.querySelector(s),key='cx-multi-screen-pages-v1-seeded',fresh=()=>window.OnlineDemo.createState();let s;try{s={...fresh(),...JSON.parse(localStorage.getItem(key)||'null')}}catch{s=fresh()}
for(const m of s.messages){if(E.copyUpdates[m.text])m.text=E.copyUpdates[m.text];}
for(const r of s.reports){if(r.date&&r.confirmed)r.dateConfirmed=true;}
if(s.auditChatStart===undefined)s.auditChatStart=s.messages.length;
if(s.request?.version!==2)s.request=null;
s.supplementAnswers ||= {};
let auditFilter='all',standardStudy='eci1';
let pPage='home',dPage='home',trial='eci1',side='p',uploadQ='',busy=false;const blobs=new Map();
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round">${({back:'<path d="m15 5-7 7 7 7"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',doc:'<path d="M6 3h8l4 4v14H6Z M14 3v5h4M9 12h6M9 16h6"/>',chat:'<path d="M20 11a8 8 0 0 1-9 8l-6 2 1-6a8 8 0 1 1 14-4Z"/><path d="M8 9h8M8 13h5"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-3a8 7 0 0 1 16 0v3"/>',bot:'<rect x="4" y="7" width="16" height="13" rx="3"/><path d="M12 3v4M8 12v2M16 12v2M9 17h6"/>'})[n]||'<circle cx="12" cy="12" r="8"/>'}</svg>`;
const b=(text,a,v='',cls='secondary')=>`<button class="${cls}" data-action="${a}" data-value="${esc(v)}">${text}</button>`;
const head=(t,who='p',back='home')=>`<header class="app-head">${b(icon('back'),who+'go',back,'icon-btn')}<h1>${t}</h1><span class="head-spacer"></span></header>`;
const pill=(t,c='')=>`<span class="pill ${c}">${esc(t)}</span>`;
const cat=id=>D.categories.find(c=>c[0]===id)||D.categories[0];
const uid=()=>crypto.randomUUID();const now=()=>new Date().toLocaleString('zh-CN');
let db;const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('cx-screen-pages-v1-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)});
async function fileStore(id,file){await dbp;return new Promise((res,rej)=>{let tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function fileGet(id){await dbp;return new Promise(res=>{const r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>res(null)})}
function save(text){if(text)s.logs.unshift({text,at:now()});localStorage.setItem(key,JSON.stringify(s));render()}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3000)}
function modal(title,body,who='p'){const el=$(who==='p'?'#patientModal':'#doctorModal');el.hidden=false;el.innerHTML=`<section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header class="sheet-head"><h2>${title}</h2>${b('×','close',who,'icon-btn')}</header>${body}</section>`}
function close(who='p'){$(who==='p'?'#patientModal':'#doctorModal').hidden=true}
function go(who,page){who==='p'?pPage=page:dPage=page;render();$(who==='p'?'#patient':'#doctor').scrollTop=0}
const reqStatus=()=>s.analyzed?'AI预审已生成':'待提交病历';
function requestCard(){if(!s.request)return '';return `<button class="card click-card request-card" data-action="pgo" data-value="chat"><div class="card-row"><span class="orb">${icon('chat')}</span><div><h3>${s.request.done?'补充内容已发给医生':'研究医生请您补充几项信息'}</h3><p>${s.request.done?'点击查看对话记录':'研究助理陪您一项项确认 · 点击开始'}</p></div><span class="chevron">›</span></div></button>`}
function followupPanel(){const pending=E.followupPlan(trial,s),active=s.request&&!s.request.done;return `<section class="card followup-panel"><h3>请患者补充信息</h3><p>针对 ${esc(D.trials.find(t=>t.id===trial).name)}，将 ${pending.length} 项可由患者回答或上传的内容合并发送。专业判断仍由研究团队完成。</p>${pending.length?`<details><summary>查看将发送的内容</summary><ol>${pending.map(q=>`<li>${esc(q.text)}</li>`).join('')}</ol></details>`:''}${active?`<p>正在补充：${s.request.index} / ${s.request.keys.length} 项完成</p>${b('查看当前患者对话','dgo','chat','secondary wide')}`:pending.length?b('一键请患者补充','requestAll','','primary wide'):'<div class="hint">本研究可由患者补充的项目已回复；暂无新问题。</div>'}${s.request&&!active?b('查看患者补充记录','dgo','chat','secondary wide'):''}<small>已答过的问题不重复发送；“暂时没有”会如实记录为仍缺资料。</small></section>`}
function home(){return `<section class="patient-hero screening-hero"><img src="assets/female-doctor.png" alt="女医生卡通研究助理"><div><h1>您好，林女士<br>每一步，都陪着您</h1><p>我是研究项目组 AI 助手</p></div></section><section class="cx-glass screening-glass"><button class="cx-spotlight gold-flow" data-action="pgo" data-value="reports"><span class="orb">${icon('doc')}</span><span><b>${s.analyzed?'入组筛选 · 资料已提交':'入组筛选 · 上传病历'}</b><small>${s.analyzed?'研究团队正在为您核对':'拍好完整病历，点击上传'}</small></span><span class="chevron">›</span></button>${requestCard()}<h2 class="cx-greeting">有想问的，我们慢慢聊。</h2><button class="cx-home-row" data-action="pgo" data-value="reports"><span class="orb">${icon('doc')}</span><span><b>${s.analyzed?'资料已提交，查看病历':'准备好病历，一起看看'}</b><small>${s.analyzed?'研究团队将基于现有材料判断':'只需上传病历，即可提交'}</small></span><span class="chevron">›</span></button><button class="cx-home-row" data-action="pgo" data-value="chat"><span class="orb">${icon('chat')}</span><span><b>有疑问，随时告诉我</b><small>关于资料和研究，慢慢聊</small></span><span class="chevron">›</span></button></section><form class="screening-composer" id="homeForm"><input id="homeQuestion" aria-label="想问研究助理的问题" placeholder="有想问的，我们慢慢聊…"><button type="button" data-action="voice" aria-label="语音输入"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg></button><button type="submit" aria-label="发送问题">➜</button></form>`}
function reportCard(r,who='p'){return `<div class="card report-card"><h3>${esc(r.name)}</h3><p>${cat(r.type)[1]} · ${esc(r.date||(r.seeded?'示例完整、最新病历':'请确认病历上的日期'))}</p>${pill(r.readable?'图片已读取':'图片不清楚，请重新上传',r.readable?'green':'red')}${who==='p'&&r.readable&&!r.seeded?`<label class="form-group">这份病历是哪一天的？<input type="date" data-report-date="${r.id}" value="${esc(r.date)}" max="${new Date().toISOString().slice(0,10)}"></label>${b(r.dateConfirmed?'日期已确认，可重新确认':'确认日期','confirmDate',r.id,'secondary wide')}`:''}<div class="action-row">${b('查看上传的图片','view',r.id,'text-btn')}</div></div>`}
function reports(){return head('上传病历与报告')+`<div class="hint">已为您准备好两张示例病历，无需重复上传。研究医生需要更多资料时，会由研究助理在聊天里告诉您。</div>${b('上传其他补充资料','upload','record','primary wide')}<div class="card known-profile"><h3>已知基本信息</h3><p>45 岁 · 女性 · ECOG 0</p><p>愿意签署研究知情同意（尚未实际签署）</p></div>${s.reports.map(r=>reportCard(r)).join('')}${current()?.kind==='upload'?b('把已确认的资料发给医生','sendFollowupReports','','primary wide'):''}${s.reports.length?b(s.analyzed?'更新资料并重新分析':'提交病历，开始预筛选','analyze','','primary wide'):''}<details class="card material-categories"><summary>如已有这些报告，也可以一起上传</summary>${D.categories.filter(c=>c[0]!=='record').map(c=>`<button class="task-row" data-action="upload" data-value="${c[0]}"><span class="task-text"><b>${c[1]}</b><small>${c[2]}</small></span><span class="chevron">›</span></button>`).join('')}</details>${requestCard()}`}
function studyOverview(){return D.trials.map(t=>{let a=E.summarize(t.id,s);return `<button class="audit-study ${a.tone}" data-action="trial" data-value="${t.id}"><div><b>${t.name}</b><span class="audit-result ${a.tone}">${a.title}</span></div><p>${esc(a.reason)}</p><small>符合 ${a.counts.pass} · 不符合 ${a.counts.fail} · 证据不足 ${a.counts.unknown} · 不适用 ${a.counts.na}</small><span class="audit-open">查看逐条证据 ›</span></button>`}).join('')}
function dHome(){return `<header class="app-head screening-d-head">${b(icon('back'),'dgo','queue','icon-btn')}<h1>研究医生工作台</h1>${b('◷','dgo','logs','icon-btn')}</header><section class="doctor-hero screening-d-hero"><div class="identity"><img src="assets/female-doctor.png" alt="女医生卡通头像"><div><span class="doctor-label">医生端 · 入组预审</span><h2>临床研究工作台</h2><p>按当前材料，逐条查看证据</p></div></div><div class="hero-count"><b>${s.analyzed?1:0}</b><span>位患者${s.analyzed?'已完成 AI 预审':'待提交病历'}</span></div><div class="hero-bottom"><span>当前执行标准</span><span>治疗史完整</span><span>最新病历</span></div></section>${s.analyzed?`<button class="screening-new-task" data-action="dgo" data-value="overview"><span class="orb">${icon('doc')}</span><span class="screening-task-copy"><strong>有一位新增患者待入组筛选</strong><small>林女士 · 病历已提交</small><em>查看 AI 预审结果</em></span><span class="chevron">›</span></button>`:'<div class="empty">患者上传并提交病历后，自动生成逐条预审。</div>'}<div class="section-title"><h2>快捷入口</h2></div><div class="quick-grid screening-quick">${[['user','患者队列','queue','已提交病例与预审'],['doc','研究标准','standards','当前执行文档原文'],['doc','病历资料','reports','原图与识别证据'],['doc','处理日志','logs','上传与分析记录']].map(x=>`<button data-action="dgo" data-value="${x[2]}"><span class="orb">${icon(x[0])}</span><strong>${x[1]}</strong><small>${x[3]}</small></button>`).join('')}</div>`}
function patientOverview(){if(!s.analyzed)return head('患者入组筛选','d')+'<div class="empty">暂无已提交病历。</div>';return head('患者入组筛选','d')+`<div class="section-title"><h2>林女士 · AI 预审</h2><small>45岁 · ECOG 0</small></div><div class="audit-lead">${E.summarize('eci1',s).counts.fail&&E.summarize('eci2',s).counts.fail?'ECI830两条路径均有明确不符合项。SPR1020有基因条件支持，但还不能确认入组。':'已根据现有材料分别判断两项研究。请查看明确结论及证据缺口。'}</div>${studyOverview()}${b('查看病历事实与逐条判断','dgo','review','primary wide')}`}
function queue(){return head('患者队列','d')+`<div class="tabs"><button class="active">待筛选</button></div>${s.analyzed?`<div class="card patient-row"><div class="details"><div><h3>患者 A</h3><div class="meta">45 岁 · 女性 · ECOG 0</div><span class="mini-id">PS-001 · ${reqStatus()}</span></div></div><div class="action-row">${pill('ECI830')}${pill('SPR1020')}</div><button class="stage-strip" data-action="dgo" data-value="overview"><span>多研究自动预审</span><span>查看详情 ›</span></button></div>`:'<div class="empty">暂无已提交资料的患者。</div>'}`}
function auditTone(r){return r.status==='符合'?'pass':r.status==='不符合'?'fail':r.status==='不适用'?'na':'unknown'}
function card(c){const r=E.evaluate(c,s),t=E.type(c),tone=auditTone(r);return `<section class="audit-criterion ${tone}"><header><span class="criterion-kind ${t}">${t==='exclusion'?'排除':'入选'}</span><h3>${esc(c.title)}</h3></header><div class="audit-status"><b>${r.status}</b><span>判断依据：${r.evidence}</span></div><div class="audit-field"><label>当前材料</label><p>${esc(r.known)}</p><small>${esc(r.basis)}</small></div><div class="audit-field"><label>判断理由</label><p>${esc(r.reason)}</p></div>${r.gaps.length?`<div class="audit-gap"><b>尚缺的判断依据</b><ul>${r.gaps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${r.supplements?.length?`<div class="supplement-evidence"><b>患者本轮补充</b>${r.supplements.map(a=>`<p>${esc(a.q.text)}<br><strong>${esc(a.label)}</strong></p><small>${esc(a.source)} · ${esc(a.at)}</small>${(a.reportIds||[]).map(id=>b(esc(s.reports.find(x=>x.id===id)?.name||'查看资料'),'view',id,'text-btn')).join('')}`).join('')}<p>已同步，仍需结合条文核对。患者自述不替代检查或医学判断。</p></div>`:''}${r.refs.length?`<details class="audit-evidence"><summary>病历摘录 · ${r.refs.length}处依据</summary>${r.refs.map(ref=>`<blockquote>${esc(ref.text)}<footer>${b(esc(ref.name)+' · 识别行 '+ref.line,'view',ref.id,'text-btn')}</footer></blockquote>`).join('')}</details>`:''}<details class="audit-original"><summary>本条入排原文</summary><p>${esc(AuditOriginals[c.id]||c.rule)}</p></details></section>`}
function review(){if(!s.analyzed)return head('AI 入组预审','d','overview')+'<div class="empty">患者尚未提交病历。</div>';const a=E.summarize(trial,s),m=E.material(s),order={'不符合':0,'证据不足':1,'符合':2,'不适用':3},rows=a.rows.filter(r=>auditFilter==='all'||r.status===auditFilter).sort((a,b)=>order[a.status]-order[b.status]);return head('AI 入组预审','d','overview')+`<section class="screen-patient"><span class="screen-avatar">林</span><div><h2>林女士 · 45岁女性</h2><p>ECOG 0 · ${m.pages.length}份病历</p></div></section><div class="audit-scope"><b>本次判断范围</b><p>当前执行文档；病历治疗记录完整、最新。证据不足保留为未确定，不等同不符合。</p><details><summary>查看已知背景与演示约定</summary><p>45岁、女性、ECOG 0为用户提供；愿意签知情为已知背景，不能替代实际签署；活检意愿由患者本轮确认，安全可行性由研究医生判断。其余项目均按当前病历证据判断；完整治疗史不等于所有检查和安全性条件均已满足。</p></details></div><div class="screen-tabs">${b('查看上传原图','dgo','reports','text-btn')}${b('研究标准原文','dgo','standards','text-btn')}${b('前往补充入口 ↓','jumpFollowup','','text-btn')}</div><details class="card audit-facts"><summary>病历事实 · 治疗时间线</summary><p>${m.adjuvant?'2021：乳腺手术后EC-T辅助化疗；之后他莫昔芬＋卵巢抑制。':'辅助治疗时间线尚未从当前材料提取完整。'}</p><p>${m.dalpi?'2024复发/转移后：阿得贝利单抗＋达尔西利＋依西美坦＋戈舍瑞林；同一联合方案，已完成22周期。':'晚期治疗记录待从原图核对。'}</p><p>${m.brca?'病历记载BRCA2胚系致病变异。':''}${m.pending?'当前主诉为“拟行疾病进展确认”，不能改写为已确认进展。':''}</p></details><div class="tabs audit-trials">${D.trials.map(t=>b(t.name,'trial',t.id,t.id===trial?'active':'')).join('')}</div><section class="audit-summary ${a.tone}"><small>${D.trials.find(t=>t.id===trial).name}</small><h2>${a.title}</h2><p>${esc(a.reason)}</p></section><div class="audit-filters">${[['all','全部',a.rows.length],['符合','符合',a.counts.pass],['不符合','不符合',a.counts.fail],['证据不足','证据不足',a.counts.unknown],['不适用','不适用',a.counts.na]].map(([v,label,n])=>b(label+' '+n,'auditFilter',v,v===auditFilter?'active':'')).join('')}</div><p class="audit-legend">结论针对入组资格：排除条目的“符合”表示未命中排除；“不符合”表示命中。判断依据充分也可能支持“不符合”。</p>${rows.length?rows.map(r=>card(r.c)).join(''):'<div class="empty">此类暂无条目</div>'}${followupPanel()}<div class="audit-footer">预审区分病历证据与患者自述。已回复或已上传不等于符合入组，最终资格由研究团队决定。</div>`}
function current(){return s.request&&!s.request.done?E.followupQuestions[s.request.keys[s.request.index]]:null}
function controls(){const q=current();if(!q)return '<div class="hint">'+(s.request?.done?'谢谢，您补充的内容已交给医生。暂时没有的资料也已记录。':'医生有需要确认的内容时，会在这里告诉您。')+'</div>';return `<section class="card chat-question"><p class="chat-progress">第 ${s.request.index+1} / ${s.request.keys.length} 项 · 可以稍后回来继续</p><h3>${esc(q.text)}</h3>${q.kind==='upload'?b('拍照 / 上传这份资料','chatUpload','','primary wide')+b('选择已经上传的资料','reuseReport','','secondary wide'):''}${q.kind==='date'?'<label class="form-group">最近一次用药日期<input id="answerDate" type="date" max="'+new Date().toISOString().slice(0,10)+'"></label>'+b('确认日期','dateAnswer','','primary wide'):''}<div class="followup-choices">${q.options.map(v=>b(esc(v),'answer',v,'secondary wide')).join('')}</div>${b('稍后再答，回首页','pgo','home','text-btn')}</section>`}
function chat(who='p'){return head(who==='p'?'研究助理':'患者补充对话',who)+`<div class="hint">${who==='p'?'我是研究团队的研究助理，替研究医生和您确认几项情况。看不懂或没有的资料，可以直接选“不确定”或“暂时没有”。':'患者答复与资料已同步；专业结论由研究团队核对。'}</div>${s.request?'<div class="chat-request-origin">来自研究医生的补充请求 · '+esc(D.trials.find(t=>t.id===s.request.trial)?.name||'')+'</div>':''}<div class="chat-stream">${s.messages.slice(s.auditChatStart||0).filter((m,i,a)=>!(who==='p'&&i===a.length-1&&m.actor==='研究助理'&&m.text===current()?.text)).map(m=>`<div class="bubble ${m.actor==='患者'?'mine':''}">${esc(m.text)}<small>${esc(m.actor)} · ${esc(m.at)}</small></div>`).join('')}</div>${who==='p'?controls():current()?`<div class="card"><h3>等待患者补充</h3><p>${esc(current().text)}</p><p>已回答 ${s.request.index} / ${s.request.keys.length} 项</p></div>`:'<div class="hint">本轮补充已结束，可返回查看各条目的新增依据。</div>'}${who==='d'?b('返回逐条预审结果','dgo','review','secondary wide'):''}`}
const standardMeta={eci1:{name:'ECI830',phase:'I 期',subtitle:'剂量递增阶段',version:'版本 04 · 2026年05月06日',protocol:'CECI830A12101'},eci2:{name:'ECI830',phase:'II 期',subtitle:'剂量扩展阶段',version:'版本 04 · 2026年05月06日',protocol:'CECI830A12101'},spr:{name:'SPR1020',phase:'SPR1020',subtitle:'晚期乳腺癌研究',version:'当前执行版',protocol:'SPR1020-S-001'}};
function standardRows(id){const order=['e1','e2','e3','e4',id==='eci1'?'e5a':'e5b','e6','e7',...Array.from({length:19},(_,i)=>'x'+(i+1))];return E.listFor(id).slice().sort((a,b)=>id==='spr'?0:order.indexOf(a.id)-order.indexOf(b.id))}
function standardParagraphs(c){let text=AuditOriginals[c.id]||c.rule;const starts={x1:['在既往任何时间','≤ 2周内','≤ 4周内接受扩大野','≤ 6周内进行','≤ 4周或','≤ 6周内接受过','对于联合治疗：'],x2:['肌酐清除率','总胆红素','丙氨酸氨基转移酶','天门冬氨酸氨基转移酶','中性粒细胞绝对计数','血小板计数','血红蛋白','筛选期ECG','研究药物首次给药前'],x3:['研究入组前6个月','有记录的心肌病','长QT综合征','尖端扭转型','有临床意义的心律失常','未受控制的动脉高血压'],x7:['患者在既往疗程中'],x16:['已知具有延长QT','CYP3A4/5的强效','具有窄治疗指数','质子泵抑制剂','草药']};for(const part of starts[c.id]||[])text=text.replace(part,'\n'+part);text=text.replace(/([。；])(?=\S)/g,'$1\n');return text.split(/\n+/).map(t=>t.trim()).filter(Boolean).map(t=>`<p>${esc(t)}</p>`).join('')}
function standardsCatalog(){return head('研究标准','d')+`<p class="standards-intro">选择研究与期别，查看对应入排原文。</p><div class="standards-catalog">${D.trials.map(t=>{const m=standardMeta[t.id],rows=standardRows(t.id),n=rows.filter(c=>E.type(c)==='exclusion').length;return `<button class="standard-study-card" data-action="standards" data-value="${t.id}" aria-label="查看${t.name}研究标准"><div class="standard-card-title"><h2>${m.name}</h2>${t.id==='spr'?'<span class="standard-phase neutral">独立研究</span>':`<span class="standard-phase">${m.phase}</span>`}</div><p class="standard-version">${m.version}</p><p class="standard-counts">${t.id==='spr'?`${rows.length} 条入组相关标准`:`入选 ${rows.length-n} 条<span>·</span>排除 ${n} 条`}</p><div class="standard-card-action">查看入排原文 <span>›</span></div></button>`}).join('')}</div>`}
function standardDetail(){const m=standardMeta[standardStudy],rows=standardRows(standardStudy),inc=rows.filter(c=>E.type(c)!=='exclusion'),exc=rows.filter(c=>E.type(c)==='exclusion');const section=(list,type,label)=>`<section class="standard-section" id="standard-${type}"><div class="standard-section-heading ${type}"><h2>${label}</h2><span>${list.length} 条</span></div><ol class="standard-clauses">${list.map((c,i)=>`<li><header><span class="standard-number ${type}">${String(i+1).padStart(2,'0')}</span><h3>${esc(c.title.replace(/^(I|II) 期：/,''))}</h3></header><div class="standard-clause-copy">${standardParagraphs(c)}</div></li>`).join('')}</ol></section>`;return head(standardStudy==='spr'?'SPR1020 研究标准':m.name+' · '+m.phase+'标准','d','standards')+`<section class="standard-detail-meta"><p>${m.version}</p><span>方案编号：${m.protocol}</span></section>${exc.length?`<nav class="standard-jumps" aria-label="标准段落">${b('入选标准 · '+inc.length,'standardJump','inclusion','secondary')}${b('排除标准 · '+exc.length,'standardJump','exclusion','secondary')}</nav>`:''}${section(inc,'inclusion',standardStudy==='spr'?'入组相关标准':'入选标准')}${exc.length?section(exc,'exclusion','排除标准'):''}<div class="standard-detail-bottom">${b('返回三个研究','dgo','standards','secondary wide')}</div>`}
function render(){let p=$('#patient').scrollTop,d=$('#doctor').scrollTop;$('#patient').innerHTML=({home,reports,chat:()=>chat('p')}[pPage]||home)();$('#doctor').innerHTML=({home:dHome,overview:patientOverview,queue,review,chat:()=>chat('d'),reports:()=>head('原图与实际识别结果','d','review')+s.reports.map(r=>reportCard(r,'d')).join(''),standards:standardsCatalog,standardDetail,logs:()=>head('处理日志','d')+`<div class="card">${s.logs.map(x=>`<div class="audit"><b>${x.at}</b><p>${esc(x.text)}</p></div>`).join('')}</div>`}[dPage]||dHome)();$('#patient').scrollTop=p;$('#doctor').scrollTop=d}
function homeAsk(text){if(!text.trim())return;addMsg('患者',text.trim());addMsg('研究助理','您的问题已记录，研究团队可在患者沟通中查看。已上传的病历不用重复提交；本次预审会直接基于您提交的现有材料进行。');pPage='chat';save('患者发来问题');}
function addMsg(actor,text){s.messages.push({actor,text,at:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})})}
function next(){s.request.index++;if(s.request.index>=s.request.keys.length){s.request.done=true;addMsg('研究助理','谢谢，您补充的内容已经发给研究医生。暂时没有的报告也已记录，后续由团队核实或安排。')}else addMsg('研究助理',current().text);save('患者补充已同步医生端');if(pPage==='chat')$('#patient').scrollTop=$('#patient').scrollHeight}
function answer(label){let q=current();if(!q)return;if(!q.options.includes(label)&&q.kind!=='date')return;s.supplementAnswers[q.id]={label,at:now(),source:q.kind==='upload'?'患者反馈资料状态':'患者自述',reportIds:[]};addMsg('患者',label);next()}
function upload(type,qid=''){uploadQ=qid;modal('上传'+cat(type)[1],`<div class="hint">请拍完整页面，避免反光、模糊和遮挡。可一次选择多张。</div><div class="upload-box"><label>选择本地图片<input id="fileInput" type="file" accept="image/jpeg,image/png,image/webp" multiple data-type="${type}"></label></div><div id="uploadStatus" role="status"></div><div id="uploadRows"></div><p class="subtle">补充图片在您的浏览器内识别与保存，不上传到服务器。首次识别需要加载组件。单张上限20MB。</p>${b('完成上传','finishUpload','','primary wide')}`)}
async function processFiles(files,type){if(busy)return;busy=true;const host=$('#uploadRows'),st=$('#uploadStatus');let added=[];try{for(let i=0;i<files.length;i++){let file=files[i];st.textContent=`正在读取第 ${i+1}/${files.length} 张图片…`;if(file.size>20*1024*1024){host.insertAdjacentHTML('beforeend','<div class="hint urgent">超过20MB，请压缩后重试。</div>');continue}let arr=await file.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',arr))].map(v=>v.toString(16).padStart(2,'0')).join('');if(s.reports.some(r=>r.hash===hash)){host.insertAdjacentHTML('beforeend',`<div class="hint urgent">${esc(file.name)}：重复图片，未重复添加。</div>`);continue}let data=await new Promise((res,rej)=>{let rd=new FileReader();rd.onload=()=>res(rd.result);rd.onerror=rej;rd.readAsDataURL(file)}),im=new Image();im.src=data;try{await im.decode()}catch{host.insertAdjacentHTML('beforeend','<div class="hint urgent">图片无法读取，请使用JPG或PNG。</div>');continue}st.textContent=`正在识别第 ${i+1}/${files.length} 张资料文字…`;let out=await WebOCR.recognize(data,progress=>{st.textContent=`正在识别第 ${i+1}/${files.length} 张资料… ${progress}`});let text=out.lines.map(x=>x.text).join('\n'),readable=text.length>=40&&Math.min(im.naturalWidth,im.naturalHeight)>=400;let r={id:uid(),name:file.name,type,hash,text,lines:out.lines.length,readable,confirmed:readable,date:'',dateConfirmed:false,quality:readable?'图片已读取':'文字不清或内容不足，请重拍',dimensions:im.naturalWidth+'×'+im.naturalHeight,qid};await fileStore(r.id,file);blobs.set(r.id,URL.createObjectURL(file));s.reports.push(r);added.push(r.id);host.insertAdjacentHTML('beforeend',`<div class="card"><h3>${esc(r.name)}</h3><p>${r.lines} 行文字已识别 · ${r.quality}</p></div>`);save('识别本地上传图片：'+r.name)}st.textContent='图片已读取。点击“完成上传”，确认病历日期即可提交。';}catch(e){st.textContent='识别未完成：'+(e.name==='TimeoutError'?'浏览器识别超时，请重试。':e.message);st.className='hint urgent'}finally{busy=false;}}
// qid is captured per upload session, never inferred from a report name.
let qid='';
async function preview(id){let r=s.reports.find(r=>r.id===id),url=blobs.get(id)||(r.seedImage?new URL(r.seedImage,location.href).href:null);if(!url){let f=await fileGet(id);if(f){url=URL.createObjectURL(f);blobs.set(id,url)}}return {r,url}}
function sendRequest(){if(s.request&&!s.request.done){go('d','chat');return toast('已有补充请求进行中，不重复发送')};const questions=E.followupPlan(trial,s);if(!questions.length)return toast('暂无新的患者补充项');s.request={version:2,trial,keys:questions.map(q=>q.id),index:0,done:false,at:now()};addMsg('研究助理','研究医生已看过您提交的病历，请我和您确认几项情况。已经写清楚的治疗经过不用再讲一遍；没有的资料也可以直接告诉我。');addMsg('研究助理',questions[0].text);save('研究医生发起补充请求：'+D.trials.find(t=>t.id===trial).name+'，'+questions.length+'项');toast('已发送，患者首页出现补充入口')}
function submitReportIds(ids){const q=current();if(!q||q.kind!=='upload')return;const rows=ids.map(id=>s.reports.find(r=>r.id===id));if(rows.some(r=>!r||!r.readable||!r.dateConfirmed))return toast('请先确认资料日期与图片可读性');rows.forEach(r=>{r.followupSubmitted=true});s.supplementAnswers[q.id]={label:'已提供 '+rows.map(r=>r.name).join('、'),at:now(),source:'患者上传资料（待核对内容）',reportIds:ids};addMsg('患者','已提供资料：'+rows.map(r=>r.name).join('、'));close();next();go('p','chat')}
async function analyze(){if(busy)return toast('请等待图片识别完成');if(!s.reports.some(r=>r.type==='record'&&r.confirmed&&r.readable&&r.dateConfirmed))return toast('请上传病历并确认病历上的日期');s.analyzed=true;dPage='review';pPage='home';save('实际上传病历已提交，按当前执行文档预审 ECI830 和 SPR1020');toast('已提交，医生端已生成逐项预审')}
const actions={
voice:()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('此浏览器暂不支持语音输入，请输入文字');const rec=new SR();rec.lang='zh-CN';rec.onresult=e=>{$('#homeQuestion').value=e.results[0][0].transcript};rec.onerror=()=>toast('未能识别语音，请输入文字');rec.start()},
pgo:v=>go('p',v),dgo:v=>go('d',v),close,analyze,
upload:v=>{qid='';upload(v)},
chatUpload:()=>{const q=current();if(!q)return;qid=q.id;upload(q.category,q.id)},
finishUpload:()=>{if(busy)return toast('正在识别图片，请稍候');close();go('p','reports')},
confirmDate:id=>{const r=s.reports.find(r=>r.id===id),date=document.querySelector(`[data-report-date="${id}"]`).value;if(!date)return toast('请先选择病历上的日期');if(date>new Date().toISOString().slice(0,10))return toast('日期晚于今天，请核实');r.date=date;r.dateConfirmed=true;r.confirmed=r.readable;save('患者确认报告日期；按当前病历证据分析');toast('日期已确认')},
view:async id=>{const {r,url}=await preview(id);modal('原图与实际识别文字',`${url?`<img class="report-preview" src="${url}" alt="用户上传的病历原图">`:''}<h3>文字识别结果</h3><p class="subtle">OCR可能有错字，原图作为核对依据。</p><div class="document"><p>${esc(r.text)}</p></div>`,side)},
auditFilter:v=>{auditFilter=v;render()},
trial:v=>{trial=v;auditFilter='all';go('d','review')},
evidence:id=>{let c=D.criteria.find(c=>c.id===id);modal('条目与病历证据',card(c),'d')},
requestAll:sendRequest,
jumpFollowup:()=>{$('#doctor .followup-panel').scrollIntoView({block:'start',behavior:'smooth'})},
reuseReport:()=>{if(!current())return;modal('选择已上传的资料',s.reports.filter(r=>r.readable&&r.dateConfirmed).map(r=>`<div class="card"><h3>${esc(r.name)}</h3><p>${esc(r.date)}</p>${b('发送这份资料','useReport',r.id,'secondary wide')}</div>`).join('')||'<p>还没有确认日期的资料，请先上传或确认。</p>')},
useReport:id=>submitReportIds([id]),
sendFollowupReports:()=>{const q=current();if(!q)return;const rows=s.reports.filter(r=>r.qid===q.id);if(!rows.length)return toast('请先上传资料，或在聊天中选择已有资料');if(rows.some(r=>!r.readable||!r.dateConfirmed))return toast('请确认每份资料的日期，并重新拍摄无法读取的图片');submitReportIds(rows.map(r=>r.id))},
answer,
dateAnswer:()=>{let v=$('#answerDate').value;if(!v)return toast('请选择日期，或选择不记得');if(v>new Date().toISOString().slice(0,10))return toast('日期不能晚于今天');answer(v)},
standards:id=>{if(!standardMeta[id])return;standardStudy=id;go('d','standardDetail')},
standardJump:type=>{$('#doctor #standard-'+type)?.scrollIntoView({block:'start',behavior:'smooth'})},
mobile:v=>{document.body.classList.toggle('mobile-doctor',v==='doctor');document.querySelectorAll('.mobile-switch button').forEach(x=>x.classList.toggle('active',x.dataset.value===v))},
reset:()=>modal('重新开始演示',`<p>将清除本次补充资料和对话，恢复为内置两张病历的初始演示状态。</p>${b('确认重新开始','confirmReset','','primary wide')}`),
confirmReset:async()=>{await dbp;db.transaction('files','readwrite').objectStore('files').clear();for(let u of blobs.values())URL.revokeObjectURL(u);blobs.clear();s=fresh();s.supplementAnswers={};pPage='home';dPage='home';close();close('d');save()},
about:()=>modal('线上演示说明','<p>本演示已内置两张示例病历，打开即可查看医生端预审。可从医生端发起补充，并在患者端体验回答或上传资料。补充资料在当前浏览器保存，双端联动为同一浏览器内的演示。</p><p>45岁、女性、ECOG0、愿意签知情是用户提供的病例背景。OCR与规则分析不能代替研究医生的正式资格判断。</p>')
};
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(e.target.closest('#doctorPhone'))side='d';else if(e.target.closest('#patientPhone'))side='p';if(el&&actions[el.dataset.action])Promise.resolve(actions[el.dataset.action](el.dataset.value)).catch(e=>toast('操作未完成，请重试：'+e.message))});
document.addEventListener('submit',e=>{if(e.target.id==='homeForm'){e.preventDefault();homeAsk($('#homeQuestion').value)}});
document.addEventListener('change',e=>{if(e.target.id==='fileInput')processFiles([...e.target.files],e.target.dataset.type)});
window.addEventListener('storage',e=>{if(e.key===key){s={...fresh(),...JSON.parse(e.newValue||'null')};render()}});
window.Demo={getState:()=>structuredClone(s),analyze,actions};render();
})();
