(()=>{
const E=Screening,P=Protocol;
const get=id=>StudyData.criteria.find(c=>c.id===id)||{id};
const all=[...P.common,...P.phase1,...P.phase2,...P.subsequent,...P.exclusion];
for(const c of all){const old=get(c.id);old.rule=c.original;}
function result(id,s){const base=E.evaluate(get(id),s),o=s.overrides?.[id];return o?{...base,status:o.status,reason:base.reason,medicalNote:o.reason,reviewed:true}:base;}
function gate(s){const rows=P.common.map(c=>({id:c.id,...result(c.id,s)}));const failed=rows.some(r=>r.status==='不符合'),open=rows.every(r=>r.status==='符合');return{rows,open,failed,title:failed?'共同条件不符合':open?'共同条件已满足':'共同条件待确认',pending:rows.filter(r=>r.status==='证据不足').map(r=>r.id)};}
function summary(t,s){const g=gate(s);if(t!=='spr'&&!g.open)return{title:g.failed?'共同条件不符合':'共同条件待确认',tone:g.failed?'fail':'unknown',reason:g.failed?'前四项共同条件存在不符合项，停止分期判断。':'先确认共同条件第 '+g.pending.map(id=>id.slice(1)).join('、')+' 项；尚未进入 I／II 期适用性判断。',rows:g.rows,counts:count(g.rows),locked:true};const rows=E.listFor(t).map(c=>({c,...result(c.id,s)}));const counts=count(rows);return{rows,counts,locked:false,title:counts.fail?'当前材料不符合':counts.unknown?'尚不能确认入组':'当前条目符合',tone:counts.fail?'fail':counts.unknown?'unknown':'pass',reason:counts.fail?rows.find(r=>r.status==='不符合').reason:t==='spr'?'BRCA2 条件有支持；HER2、治疗失败、可测量病灶等证据仍不足。':'全部适用条目还需完成逐项证据核对。'};}
function count(rows){return{pass:rows.filter(r=>r.status==='符合').length,fail:rows.filter(r=>r.status==='不符合').length,unknown:rows.filter(r=>r.status==='证据不足').length,na:rows.filter(r=>r.status==='不适用').length};}
function plan(t,s){const g=gate(s);if(t!=='spr'&&g.failed)return[];const ids=new Set((t!=='spr'&&!g.open?g.rows:E.listFor(t).map(c=>({id:c.id,...result(c.id,s)}))).filter(r=>r.status==='证据不足').map(r=>r.id));const order=t!=='spr'&&!g.open?P.common.map(c=>c.id):E.listFor(t).map(c=>c.id);return Object.values(E.followupQuestions).filter(q=>q.criteria.some(id=>ids.has(id))&&!s.supplementAnswers[q.id]).sort((a,b)=>Math.min(...a.criteria.filter(id=>ids.has(id)).map(id=>order.indexOf(id)))-Math.min(...b.criteria.filter(id=>ids.has(id)).map(id=>order.indexOf(id))));}
function sendRequest(t,s,from){if(s.request&&!s.request.done)return false;const qs=plan(t,s);if(!qs.length)return false;s.request={trial:t,keys:qs.map(q=>q.id),index:0,done:false,from};s.messages.push({role:'assistant',text:`您好，我是${from}的研究助理。医生看过您的病历了，有${qs.length}件事想和您确认，我们一项一项来。`});s.messages.push({role:'assistant',text:qs[0].text});return true;}
function answer(s,label,reportIds=[]){const req=s.request;if(!req||req.done)return false;const id=req.keys[req.index];s.supplementAnswers[id]={label,reportIds,at:new Date().toLocaleString(),source:reportIds.length?'患者上传':'患者本轮自述'};s.messages.push({role:'patient',text:label});req.index++;if(req.index>=req.keys.length){req.done=true;s.messages.push({role:'assistant',text:'谢谢，您补充的内容已交给研究医生。需要医生看报告才能判断的项目，我们会继续核对，有消息会告诉您。'});}else s.messages.push({role:'assistant',text:E.followupQuestions[req.keys[req.index]].text});return true;}
window.Audit={result,gate,summary,plan,sendRequest,answer,count,get,all};
})();
