/* ECI830 only: shared clauses once; both phase-specific clauses on one page. */
const originalUploadFiles=uploadFiles,originalCommitUpload=commitUpload;
const Reference={trials:['eci1'],fixture:OnlineDemo.createState().reports};
const studyName=()=> 'ECI830 · I期 / II期';
function studyResult(){const g=Audit.gate(state),a=uiStats('eci1'),b=uiStats('eci2');return{label:g.failed?'不符合':!g.open?'待补充':a.fail&&b.fail?'不符合':(!a.fail&&!a.pending)||(!b.fail&&!b.pending)?'符合':'待补充',pass:g.rows.filter(r=>r.status==='符合').length,total:4,caption:'共同条件通过',reason:g.failed?'共同条件不符合，不能进入I/II期。':g.open?'共同条件已满足，继续核对I/II期条件。':'共同条件第'+g.pending.map(id=>id.slice(1)).join('、')+'项待补充；暂不能确认进入I/II期。'}}
function combinedRows(){return [...Protocol.common,Protocol.phase1[0],Protocol.phase2[0],...Protocol.subsequent,...Protocol.exclusion]}
function combinedStats(){const rows=combinedRows().map(c=>Audit.result(c.id,state));return{pass:rows.filter(r=>r.status==='符合').length,total:rows.filter(r=>r.status!=='不适用').length}}
const oldEvaluate=Screening.evaluate;
Screening.evaluate=(c,s)=>s.caseMatched?oldEvaluate(c,s):({status:'证据不足',known:s.reports.length?'已收到部分资料，尚未确认两张指定病历均已上传。':'尚未上传患者病历。',reason:'只有实际上传与指定病例对应的两张图片后，才使用该病例的已知背景和证据进行审核。',gaps:['两张指定病历图片'],refs:[],supplements:[]});
function displayStatus(s){return s==='证据不足'?'待补充':s}
function uiStats(t){const rows=Screening.listFor(t).map(c=>({c,...Audit.result(c.id,state)}));return{rows,pass:rows.filter(r=>r.status==='符合').length,fail:rows.filter(r=>r.status==='不符合').length,pending:rows.filter(r=>r.status==='证据不足').length,na:rows.filter(r=>r.status==='不适用').length,total:rows.filter(r=>r.status!=='不适用').length}}
function groupCounts(rows){const counts=Audit.count(rows.map(c=>Audit.result(c.id,state)));return `<span class="decision-summary">${counts.pass?`<em class="pass">${counts.pass}</em>`:''}${counts.fail?`<em class="fail">${counts.fail}</em>`:''}${counts.unknown?`<em class="unknown">${counts.unknown}</em>`:''}</span>`}
function verdict(status,id){const label=displayStatus(status),t=tone(status);return `<button class="decision-control is-${t}" data-review="${id}" aria-label="${label}，查看本条判断"><span class="decision-icon">${status==='符合'?icon('check'):status==='不符合'?'×':status==='不适用'?'—':''}</span><small>${label}</small></button>`}
function sourceMarks(r){const refs=[...new Map((r.refs||[]).map(x=>[x.id,x])).values()];return refs.length?`<sup class="criterion-reference-marks">[${refs.map(x=>`<button data-preview="${x.id}" data-evidence-lines="${(r.refs||[]).filter(ref=>ref.id===x.id).map(ref=>ref.line).join(',')}" aria-label="查看病历来源 ${x.name}">${state.reports.findIndex(p=>p.id===x.id)+1}</button>`).join(',')}]</sup>`:''}
function inlineTree(n){return `<div class="standard-text">${renderTree(n,true)}</div>`}
function decisionRow(c){const r=Audit.result(c.id,state),n=c.number||'',exclude=c.id.startsWith('x');let tree=c.tree?displayTree(c):{tag:'p',text:c.original||c.rule,children:[],tail:''};if(/^e[1-4]$/.test(c.id))tree.text=tree.text.replace(/^\d+[.．]\s*/,'');return `<div class="decision-row is-${tone(r.status)}" data-criterion="${c.id}"><span class="criterion-number ${exclude?'exclude':''}">${exclude?'排':'入'}${/^\d+$/.test(n)?n.padStart(2,'0'):esc(n)}</span><div class="decision-copy"><button class="criterion-text" data-evidence="${c.id}" aria-label="查看第${esc(n)}条证据">${inlineTree(tree)}</button>${sourceMarks(r)}</div><div class="decision-verdict">${verdict(r.status,c.id)}</div></div>`}
function decisionGroup(title,rows,open){return `<details class="decision-group" ${open?'open':''}><summary class="decision-group-head"><span><b>${title}</b><small>${rows.length} 项</small></span>${groupCounts(rows)}<span class="fold">⌄</span></summary><div class="decision-list">${rows.map(decisionRow).join('')}</div></details>`}
function reviewContent(){const m=combinedStats(),g=Audit.gate(state),inc=[...Protocol.common,Protocol.phase1[0],Protocol.phase2[0],...Protocol.subsequent],status=studyResult().label;return `<h2 class="review-title">入排标准明细</h2><div class="review-summary">${badge(status,tone(status==='待补充'?'证据不足':status))}<div><strong>${m.pass}/${m.total}</strong><small>已通过条目 · 两期合并去重</small></div></div><p class="review-caption">共同条件只列一次；I期、II期特异性条件分别核对。</p><div class="decision-legend"><span class="pass">✓ 符合</span><span class="fail">× 不符合</span><span class="unknown"><i></i>待补充</span><small>点击状态可查看</small></div><div class="consent-review-note"><span>ⓘ</span><div><b>先核对共同条件，再判断I/II期适用性</b><p>${esc(studyResult().reason)}</p></div></div><section class="decision-group"><div class="decision-group-head"><span><b>入选标准</b><small>8 项 · 两期特异性条件均列出</small></span>${groupCounts(inc)}<span>⌄</span></div><div class="decision-list"><div class="hierarchy-heading">共同入选条件 · 1—4</div>${Protocol.common.map(decisionRow).join('')}<div class="hierarchy-heading">I期 · BC 乳腺癌特异性条件</div>${decisionRow({...Protocol.phase1[0],number:'I'})}<div class="hierarchy-heading">II期 · BC 乳腺癌特异性条件</div>${decisionRow({...Protocol.phase2[0],number:'II'})}<div class="hierarchy-heading">共同后续入选条件 · 5—6</div>${Protocol.subsequent.map(c=>decisionRow({...c,number:c.id==='e6'?'05':'06'})).join('')}</div></section>${decisionGroup('共同排除标准',Protocol.exclusion,false)}<div class="review-caption">男性专属第18条不适用，不计入通过数。合并计数用于展示条目核对情况，不能据此确认进入任何一期。</div><details class="decision-group"><summary class="decision-group-head"><b>其他适应症分支原文</b><span></span><span>⌄</span></summary><div class="notice">保留I期其他适应症原文，未纳入当前乳腺癌条件的通过数。</div><div class="original-all">${Protocol.phase1.slice(1).map(c=>original(c)).join('')}</div></details><div class="review-actions">${btn('一键请患者补充','request:eci1','secondary')}${role==='pi'?btn('记录I期处理意见','decision:eci1','primary mt')+btn('记录II期处理意见','decision:eci2','primary mt'):btn('推荐给项目 PI','recommend-selected','primary mt')}${btn('查看标准原文','project:eci1','link mt')}</div>`}
function reviewPage(){return `${identity()}<div class="review-project-card"><span class="project-flask"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M9 3h6M10 3v6L5 19a1.5 1.5 0 0 0 1.3 2h11.4a1.5 1.5 0 0 0 1.3-2L14 9V3M8 14h8"/></svg></span><div><small>复核项目</small><b>${studyName(trial)}</b><p>晚期乳腺癌及实体瘤研究</p><span>本人主动筛选</span></div></div><div class="review-tabs">${[['matches','入排明细'],['info','患者信息'],['materials','患者材料']].map(([k,t])=>`<button class="${subtab===k?'active':''}" data-tab="${k}">${t}</button>`).join('')}</div>${subtab==='info'?archiveOverview():subtab==='materials'?materials():reviewContent()}`}
identity=()=>`<div class="review-patient"><span class="avatar">林</span><div class="grow"><small>DX-CASE-001</small><h1>林女士 · 45 岁</h1><p>乳腺癌复发／转移 · ECOG 0</p></div><span class="badge unknown">待复核</span></div>`;
sidebar=()=>{const r=activeRole();$('#control').innerHTML=`<div class="eyebrow">DEMO CONTROL</div><h2>演示控制台</h2><div class="control-note">仅用于评审，不属于 Dx APP</div><div class="identity"><span class="avatar">${r[0]}</span><div><small>当前身份</small><br><b>${r[1]} · ${r[2]}</b><br><small>${role==='screener'?'乳腺肿瘤门诊':'早期临床研究中心'}</small></div></div>${[['项目管理','manager'],['初筛','screener'],['项目 PI','zhou']].map(g=>`<div class="role-label">${g[0]}</div>${g.slice(1).map(k=>`<button class="role ${(role==='pi'?pi:role)===k?'active':''}" data-role="${k}"><span class="avatar">${roles[k][0]}</span><span class="grow">${roles[k][1]}<small>${roles[k][3]}</small></span>${(role==='pi'?pi:role)===k?'✓':''}</button>`).join('')}`).join('')}<div class="control-foot"><b>患者档案自动筛选</b><p class="muted mt">每日筛选${state.schedule?'已开启':'已关闭'}，可在科研中心设置；云端定时尚未启用。</p>${btn('演示一次每日筛选','match','outline mt')}<p class="muted mt">匹配初筛医生绑定患者与全部招募项目，由医生选择推荐，不自动推送 PI。</p></div><div class="control-foot">${btn('重新开始','reset','outline')}${btn('演示说明','about','link mt')}</div>`};
home=()=>{const rec=Object.keys(state.recommendations).length;return `${role!=='screener'?`<div class="task"><div class="grow"><p>入组待办</p><strong>${rec}</strong><small>项待复核</small></div>${btn('查看待办','tasks')}</div>`:''}<div class="screener-upload"><h2>门诊初筛</h2>${btn(icon('camera')+' 拍照/上传资料','upload')}<div class="grid2 mt">${btn(icon('scan')+'<span>一键匹配<small>我的患者档案</small></span>','match','secondary')}${btn(icon('clock')+`<span>定时筛选<small>${state.schedule?'已开启':'已关闭'}</small></span>`,'schedule','secondary')}</div>${btn('试用演示病例','upload','link mt')}</div><button class="patient-match" data-action="match">患者库匹配结果 <span>${state.analyzed?'1':'0'} 位患者 ›</span></button><div class="metrics"><div><strong>1</strong><small>可筛项目</small></div><div><strong>${state.analyzed?'1':'0'}</strong><small>患者档案</small></div><div><strong>${rec}</strong><small>待 PI 处理</small></div></div><div class="section-title"><h2>正在招募</h2>${btn('全部','projects','link')}</div>${Reference.trials.map(t=>`<button class="recruit-card" data-project="${t}"><span class="avatar">EC</span><span class="grow"><b>${studyName(t)}</b><small>早期临床研究中心 · ${owner(t)}</small></span>${badge('招募中','pass')}</button>`).join('')}<div class="section-title"><h2>最近筛选</h2>${btn('查看看板','results','link')}</div>${state.analyzed?`<button class="recruit-card" data-action="results"><span class="avatar">林</span><span class="grow"><b>林女士 <small>DX-CASE-001</small></b><small>两张病历已提交 · ECI830 I/II期条件已核对</small></span>${badge('已完成','pass')}</button>`:`<div class="empty">还没有筛选记录<br>请先上传患者的两张病历照片</div>`}<p class="footer-note">匹配结果仅用于初筛，最终由项目 PI 确认正式入组。</p>`};
resultsContent=()=>{const r=studyResult();return `<h2 class="review-title">ECI830 · 患者筛选结果</h2><article class="match-project" data-study="eci"><div class="row"><div class="grow"><h3>${studyName()}</h3></div>${badge(r.label,tone(r.label==='待补充'?'证据不足':r.label))}</div><p>${r.pass}/${r.total} ${r.caption}</p><p>${esc(r.reason)}</p><div class="study-phase-results">${['eci1','eci2'].map(p=>{const m=uiStats(p);return `<div class="phase-result"><b>${p==='eci1'?'I期':'II期'}</b><span>${m.fail?'存在不符合条目':m.pending?'待补充':'条目符合'} · ${m.pass}/${m.total} 通过</span></div>`}).join('')}<small>${Audit.gate(state).open?'共同条件已满足，分别核对两期后续条款。':'共同条件未齐，暂不确认入组。'}</small></div><button class="link" data-review-project="eci1">查看I期 / II期全部条目 ›</button></article>`};
matches=()=>!state.analyzed?`<div class="empty">请先上传两张病历照片，再查看对应判断。</div>${btn('拍照/上传资料','upload','primary mt')}`:`${identity()}<div class="review-tabs">${[['matches','匹配结果'],['info','患者信息'],['materials','患者材料']].map(([k,v])=>`<button data-tab="${k}" class="${subtab===k?'active':''}">${v}</button>`).join('')}</div>${subtab==='info'?archiveOverview():subtab==='materials'?materials():resultsContent()}`;
const oldArchiveOverview=archiveOverview;
archiveOverview=()=>{let html=oldArchiveOverview();const start=html.indexOf('<h2>研究入组状态');if(start>=0)html=html.slice(0,start)+`<h2>研究入组状态</h2>${Reference.trials.map(t=>`<div class="flat-card"><b>${studyName(t)}</b><p class="small mt">${esc(studyResult(t).label)}</p>${btn('查看入组复核','open-review:'+t,'link mt')}</div>`).join('')}`;return html};
const oldPatientPage=patientPage;
patientPage=()=>state.analyzed?oldPatientPage():`<div class="patient-hero patient-welcome"><div class="brand">橙</div><h1>橙欣健康</h1><p class="muted small">你身边的乳腺健康管家</p><h2>等待医生邀请</h2><p class="muted small">医生展示邀请二维码后，扫码完成注册并绑定。</p>${btn('演示扫码','demo-scan','primary mt')}<p class="muted small mt">演示请使用指定病例资料</p></div>`;
upload=()=>`<div class="upload-instructions"><h2>请拍摄完整、清晰的页面</h2><p>避免反光、遮挡和画面抖动。</p></div><h2>建议材料</h2><div class="tags mb">${['病理报告','既往治疗记录','影像报告','近期检验','基因或免疫组化报告'].map(t=>`<span>${t}</span>`).join('')}</div><div class="upload-zone">${icon('camera')}<p>拍摄或选择材料</p><small>可多选照片</small><input type="file" accept="image/*" multiple aria-label="选择患者材料" id="doctor-upload"></div><div class="upload-hint">本次请上传指定的两张病历照片。上传后再显示该病例的入排判断。</div>${state.reports.length?`<div class="uploaded-files">${state.reports.map(r=>`<div class="row record"><button data-preview="${r.id}">${esc(r.name)}</button>${badge(r.confirmed?'已提交':'待确认','pass')}</div>`).join('')}</div>${btn('查看匹配结果','match','primary mt')}`:''}`;
const oldRender=render;
render=()=>{sidebar();const names={home:'科研中心',review:'入组复核',results:'匹配结果',tasks:'入组待办',archive:'患者档案',project:'项目详情',projects:'研究项目',patients:'患者列表',upload:'上传患者材料',notifications:'协作消息'};$('#dhead').innerHTML=`<button data-action="${view==='home'?'menu':view==='review'?'results':'home'}" aria-label="${view==='home'?'打开菜单':'返回'}">${icon(view==='home'?'menu':'back')}</button><span>${names[view]||'科研中心'}</span><button data-action="notifications" aria-label="消息通知">${icon('bell')}${state.notifications.length?`<i class="notification-dot">${state.notifications.length}</i>`:''}</button>`;$('#doctor').classList.toggle('reference-review',view==='review');$('#doctor').innerHTML=view==='home'?home():view==='review'?reviewPage():view==='results'?matches():view==='tasks'?tasksPage():view==='archive'?(state.analyzed?archive():matches()):view==='project'?project():view==='projects'?'<h1>研究项目</h1>'+Reference.trials.map(t=>projectCard(t).replace(titles[t],studyName(t))).join(''):view==='patients'?matches():view==='upload'?upload():notices();$('#phead').innerHTML=`<button data-action="patient-home" aria-label="患者端返回">${icon('back')}</button><span>${patientView==='chat'?'研究助理':patientView==='documents'?'我的资料':'橙欣健康'}</span><span style="width:30px"></span>`;$('#patient').innerHTML=patientPage();document.body.dataset.mobile=mobile;if(renderedView!==view)$('#doctor').scrollTop=0;if(renderedPatient!==patientView)$('#patient').scrollTop=0;renderedView=view;renderedPatient=patientView;};
function openReview(t){if(!state.analyzed)return navigate('upload');trial='eci1';subtab='matches';navigate('review')}
review=id=>{const c=Audit.all.find(c=>c.id===id),r=Audit.result(id,state);modal('本条入排判断',`<span class="badge ${tone(r.status)}">${displayStatus(r.status)}</span><div class="evidence"><b>标准原文</b><div class="original-all">${original(c)}</div><b>患者病历已知内容</b><p>${esc(r.known)}</p><b>判断理由</b><p>${esc(r.reason)}</p>${r.gaps?.length?`<b>待补充的依据</b><ul>${r.gaps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${refsHTML(r)}${r.supplements?.length?`<b>患者补充</b>${r.supplements.map(a=>`<p>${esc(a.label)}</p>`).join('')}`:''}</div><details class="mt"><summary>记录医生判断</summary><label>判断结果<select id="review-status">${['符合','证据不足','不符合','不适用'].map(v=>`<option value="${v}" ${v===r.status?'selected':''}>${displayStatus(v)}</option>`).join('')}</select></label><label>依据与理由<textarea id="review-reason">${esc(state.overrides[id]?.reason||'')}</textarea></label>${btn('保存判断','save-review:'+id)}${state.overrides[id]?btn('恢复原始判断','restore-review:'+id,'outline mt'):''}</details>`)};
const previousAction=action;
action=a=>{if(a==='match'||a==='results'){if(!state.caseMatched){if(state.reports.length)toast('请上传两张指定病例照片后，再核对该病例的标准');navigate('upload');return}state.analyzed=true;save();navigate('results');return}if(a==='recommend-selected'){if(!Audit.gate(state).open)return toast('前四项共同条件仍需补充，暂不进入分期推荐');if(uiStats(trial).fail)return toast('该研究存在明确不符合项，不能推荐入组');state.selected=[trial];return previousAction('recommend')}if(a.startsWith('open-review:')||a.startsWith('task:'))return openReview(a.split(':')[1]);if(a==='demo-scan'){toast('请由医生端上传两张病历，提交后患者端同步展示');return}if(a==='reset'){modal('重新开始',`<p>恢复内置的两张示例病历和ECI830初筛结果，清除本次补充对话和操作记录。</p>${btn('确认重新开始','confirm-reset','primary mt')}`);return}if(a==='about'){modal('演示说明',`<p>王医生名下为 ECI830。I期、II期特异性条件在同一页核对，共同条件和排除标准只列一次。线上版已载入两张原始病历，直接展示ECI830 I/II期判断；可查看原图和继续补充资料。</p><p class="notice">指定照片按文件内容校验，复用已经核对的识别文本。不是凭文件名识别，也不会把任意图片当成此病例。</p><p class="small">缺少证据显示“待补充”。分期条目保留条件性核对结论；前四项不满足时不进入分期推荐。AI初判、医生判断与患者补充分别记录。只在此浏览器内模拟联动。</p>`);return}return previousAction(a)};
async function fixedHash(file){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(b=>b.toString(16).padStart(2,'0')).join('')}
uploadFiles=async(files,patient)=>{if(patient&&state.caseMatched)return originalUploadFiles(files,patient);if(busy)return;busy=true;draftUploads=[];modal('正在检查照片','<p>正在核对图片内容、清晰尺寸和重复文件…</p>');try{for(const f of files){if(!f.type.startsWith('image/')){toast('请选择图片文件');continue}const hash=await fixedHash(f);if([...state.reports,...draftUploads].some(r=>r.hash===hash)){toast('这张照片已经上传，请勿重复选择');continue}const known=Reference.fixture.find(r=>r.hash===hash);const id=known?.id||'upload-'+Date.now()+'-'+draftUploads.length;await filePut(id,f);const bitmap=await createImageBitmap(f),small=Math.min(bitmap.width,bitmap.height)<600;bitmap.close();const r={id,name:f.name,hash,text:known?.text||'',type:'record',confirmed:false,knownFixed:!!known,quality:known?'已匹配指定病例原图':'不是本次指定的病例照片',small,patient,date:'',previewURL:URL.createObjectURL(f)};draftUploads.push(r)}if(!draftUploads.length){closeModal();return}modal('确认上传材料',`${draftUploads.map((r,i)=>`<div class="upload-review"><img src="${r.previewURL}" alt="已选择的病历照片"><b>${esc(r.name)}</b><p class="small">${esc(r.quality)}</p><label>图像质量<select id="upload-quality-${i}"><option value="ok">清晰，相关内容完整</option><option value="blur">模糊，需要重拍</option><option value="missing">缺页或报告不完整</option><option value="covered">关键信息遮挡</option></select></label><label>病历日期<input type="date" id="upload-date-${i}"></label></div>`).join('')}<p class="small">日期不清楚可留空；文件名不作为病历日期。</p>${btn('提交并匹配研究','commit-upload','primary mt')}`)}catch(e){modal('照片读取失败',`<p>${esc(e.message||'请重新选择照片')}</p>`)}finally{busy=false}};
commitUpload=()=>{if(draftUploads.some(r=>r.patient)&&state.caseMatched)return originalCommitUpload();if(draftUploads.some((r,i)=>$('#upload-quality-'+i).value!=='ok'))return toast('请先补齐或重拍存在问题的照片');for(let i=0;i<draftUploads.length;i++){const r=draftUploads[i];r.date=$('#upload-date-'+i).value;r.confirmed=true;r.followupSubmitted=true;delete r.previewURL;state.reports.push(r)}state.caseMatched=Reference.fixture.every(f=>state.reports.some(r=>r.hash===f.hash&&r.confirmed));state.analyzed=state.caseMatched;state.invited=state.caseMatched;state.logs.unshift({text:state.caseMatched?'两张指定病例照片已上传，已完成 ECI830 I/II期条目核对。':'已保存照片，等待上传另一张指定病例。',at:new Date().toLocaleString()});save();closeModal();draftUploads=[];patientView='home';if(state.caseMatched){trial='eci1';subtab='matches';navigate('results');toast('两张病历上传完成，已生成ECI830 I/II期判断')}else{navigate('upload');toast('材料已保存，请继续选择另一张指定病例照片')}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reviewProject)openReview(b.dataset.reviewProject);if(b.dataset.evidence)review(b.dataset.evidence)});
render();
